export enum Medication {
	// Обезболивающие и противовоспалительные
	PARACETAMOL = 1,
	IBUPROFEN = 2,
	ASPIRIN = 3,
	DICLOFENAC = 4,
	KETOPROFEN = 5,
	NAPROXEN = 6,
	NIMESULIDE = 7,
	MELOXICAM = 8,

	// Антибиотики
	AMOXICILLIN = 9,
	AZITHROMYCIN = 10,
	CIPROFLOXACIN = 11,
	CLARITHROMYCIN = 12,
	DOXYCYCLINE = 13,
	CEPHALEXIN = 14,
	METRONIDAZOLE = 15,
	AMOXICILLIN_CLAVULANATE = 16,

	// Антигистаминные
	LORATADINE = 17,
	CETIRIZINE = 18,
	DESLORATADINE = 19,
	FEXOFENADINE = 20,
	LEVOCETIRIZINE = 21,

	// Препараты для ЖКТ
	OMEPRAZOLE = 22,
	PANTOPRAZOLE = 23,
	RANITIDINE = 24,
	DOMPERIDONE = 25,
	METOCLOPRAMIDE = 26,
	LACTULOSE = 27,
	BISACODYL = 28,
	LOPERAMIDE = 29,

	// Сердечно-сосудистые препараты
	AMLODIPINE = 30,
	ATENOLOL = 31,
	BISOPROLOL = 32,
	ENALAPRIL = 33,
	LOSARTAN = 34,
	VALSARTAN = 35,
	ATORVASTATIN = 36,
	ROSUVASTATIN = 37,
	SIMVASTATIN = 38,
	ASPIRIN_CARDIO = 39,
	CLOPIDOGREL = 40,

	// Препараты для дыхательной системы
	SALBUTAMOL = 41,
	BUDESONIDE = 42,
	FLUTICASONE = 43,
	AMBROXOL = 44,
	BROMHEXINE = 45,
	ACETYLCYSTEINE = 46,

	// Противодиабетические препараты
	METFORMIN = 47,
	GLIBENCLAMIDE = 48,
	GLICLAZIDE = 49,
	INSULIN_GLARGINE = 50,
	INSULIN_ASPART = 51,

	// Гормональные препараты
	LEVOTHYROXINE = 52,
	PREDNISOLONE = 53,
	DEXAMETHASONE = 54,
	HYDROCORTISONE = 55,

	// Витамины и минералы
	VITAMIN_D3 = 56,
	VITAMIN_B12 = 57,
	FOLIC_ACID = 58,
	IRON_SULFATE = 59,
	CALCIUM_CARBONATE = 60,
	MAGNESIUM_B6 = 61,
	MULTIVITAMIN = 62,

	// Неврологические препараты
	DIAZEPAM = 63,
	ALPRAZOLAM = 64,
	GABAPENTIN = 65,
	PREGABALIN = 66,
	CARBAMAZEPINE = 67,

	// Антидепрессанты
	SERTRALINE = 68,
	ESCITALOPRAM = 69,
	FLUOXETINE = 70,
	VENLAFAXINE = 71,

	// Противовирусные
	ACYCLOVIR = 72,
	OSELTAMIVIR = 73,
	VALACICLOVIR = 74,

	// Противогрибковые
	FLUCONAZOLE = 75,
	CLOTRIMAZOLE = 76,
	TERBINAFINE = 77,

	// Препараты для мочеполовой системы
	TAMSULOSIN = 78,
	SILDENAFIL = 79,
	TADALAFIL = 80,
	DROTAVERINE = 81,

	// Офтальмологические препараты
	TIMOLOL = 82,
	LATANOPROST = 83,
	ARTIFICIAL_TEARS = 84,

	// Антисептики и дезинфицирующие средства
	CHLORHEXIDINE = 85,
	HYDROGEN_PEROXIDE = 86,
	IODINE_SOLUTION = 87,

	// Другие препараты
	INSULIN_NPH = 88,
	WARFARIN = 89,
	ALLOPURINOL = 90,
	COLCHICINE = 91,
	FUROSEMIDE = 92,
	SPIRONOLACTONE = 93,
	DIGOXIN = 94,
	NITROGLYCERIN = 95,
	ISOSORBIDE_MONONITRATE = 96,
	TRAMADOL = 97,
	CODEINE = 98,
	MORPHINE = 99,
	BACLOFEN = 100,
}
