-- Tariff insert: fzocg-apotekarska
-- Source: data/fzocg/apotekarska-djelatnost/apotekarska-djelatnost-FINAL.json (40 items)
-- Generated by scripts/fzocg/generate_tariff_sql.py
-- Run: mysql -u root -p --default-character-set=utf8mb4 docta_me < server/sql/insert-tariff-fzocg-apotekarska.sql

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET CHARACTER SET utf8mb4;

-- rows 1..40
INSERT INTO `medical_service_tariffs` (`tariff_source`, `code`, `scheme`, `price_eur`, `price_odjeljenje_eur`, `price_ambulanta_eur`, `price_operacija_eur`, `price_anestezija_eur`, `price_ukupno_eur`, `coefficient`, `base_coefficient_eur`, `name_sr_latin`, `section`, `subsection`, `amended_from`, `effective_from`, `source_signed_number`, `source_pdf`, `notes`) VALUES
('fzocg-apotekarska', '10', 'single', 0.78, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izdavanje ampuliranog lijeka', 'USLUGE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '20', 'single', 0.67, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izdavanje gotovog lijeka', 'USLUGE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '30', 'single', 0.72, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izdavanje magistralnog lijeka', 'USLUGE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '40', 'single', 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izdavanje opojne droge', 'USLUGE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '50', 'single', 0.67, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izdavanje medicinskog pomagala', 'USLUGE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '1', 'single', 0.83, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje antibiotskih sirupa', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '50-RT', 'single', 0.64, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mjerenje jedne supstance do 1000 g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, 'Izvorni kod: 50 (sekcija: RADNE TAKSE). Kod izmijenjen u 50-RT radi jedinstvenosti (isti kod postoji u drugoj sekciji).'),
('fzocg-apotekarska', '480', 'single', 2.63, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pulveres mixti', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '180', 'single', 3.91, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izrada suspenzija do 200 g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '430', 'single', 1.93, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lotiones', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '560', 'single', 3.96, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unguentae/emul', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '570', 'single', 2.63, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unguentae/susp', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '550', 'single', 2.63, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unguentae/otop', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '470', 'single', 4.96, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pastae', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '70', 'single', 1.55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje lijeka u hladnu ili toplu tečnost', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '60', 'single', 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje dvije ili više tečnosti do 1000g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '370', 'single', 3.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Emulsiones', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '310', 'single', 5.98, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Izrada lijeka pod asept. uslovima', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '601', 'single', 1.04, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje alkohola sa vodom do 100g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '602', 'single', 1.07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje alkohola sa vodom do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '603', 'single', 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje alkohola sa vodom do 300g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '604', 'single', 1.15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje alkohola sa vodom do 500g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '605', 'single', 1.36, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje alkohola sa vodom do 1000g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '606', 'single', 1.08, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 100g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '607', 'single', 1.19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '608', 'single', 1.26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 300g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '609', 'single', 1.46, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 500g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '610', 'single', 1.93, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 1000g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '701', 'single', 1.66, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje acidi borici u vodi do 100g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '702', 'single', 1.76, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje acidi borici u vodi do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '703', 'single', 1.87, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje acidi borici u vodi do 300g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '704', 'single', 2.05, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje acidi borici u vodi do 500g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '705', 'single', 2.54, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje acidi borici u vodi do 1000g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '706', 'single', 1.66, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje rivanola u vodi do 100g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '707', 'single', 1.76, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje rivanola u vodi do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '708', 'single', 1.87, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje rivanola u vodi do 300g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '709', 'single', 2.08, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje rivanola u vodi do 500g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '710', 'single', 2.59, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje rivanola u vodi do 1000g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '711', 'single', 1.61, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje jedne ili više supstanci u tečnost do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '561', 'single', 4.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unguentae/emul sa vodom', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE `scheme` = VALUES(`scheme`), `price_eur` = VALUES(`price_eur`), `price_odjeljenje_eur` = VALUES(`price_odjeljenje_eur`), `price_ambulanta_eur` = VALUES(`price_ambulanta_eur`), `price_operacija_eur` = VALUES(`price_operacija_eur`), `price_anestezija_eur` = VALUES(`price_anestezija_eur`), `price_ukupno_eur` = VALUES(`price_ukupno_eur`), `coefficient` = VALUES(`coefficient`), `base_coefficient_eur` = VALUES(`base_coefficient_eur`), `name_sr_latin` = VALUES(`name_sr_latin`), `section` = VALUES(`section`), `subsection` = VALUES(`subsection`), `amended_from` = VALUES(`amended_from`), `effective_from` = VALUES(`effective_from`), `source_signed_number` = VALUES(`source_signed_number`), `source_pdf` = VALUES(`source_pdf`), `notes` = VALUES(`notes`);
