-- ═══════════════════════════════════════════════════════════════════════════
-- Moj Lab: перечень анализов сети → 9 лабораторий, без цен (2026-10-02)
-- Применять ПОСЛЕ insert-clinics-moj-lab-network-2026-10.sql (лаборатории оттуда).
--
-- Источник: https://mojlab.me/laboratorija — вкладки «Biohemija i imunologija»,
-- «Mikrobiologija», «Patohistologija», «Molekularna dijagnostika i gene».
-- Снимок: data/clinic-pricelists/sources/moj-lab-laboratorija-podgorica-moskovska/2026-10-02.html
-- Цен на сайте нет нигде (проверено 2026-10-02) — price = NULL у всех строк.
-- Перечень один на сеть, к локации на сайте не привязан; решение юзера —
-- растянуть на все лаборатории сети (поликлиники, педиатрии и больница — нет).
--
-- Цифры: в источнике 742 строки, 724 уникальные позиции. Совпало с каталогом —
-- 453 записей lab_tests (по точному имени или синониму — 202, остальное
-- сопоставлено вручную; несколько строк сайта бывают одной записью: «INR» и
-- «Protrombinsko vrijeme» и т.п.).
-- НЕ здесь: new 172, unclear 80, not_labtest 10 —
-- см. data/clinic-imports/moj-lab-labtests-2026-10.md, ждут решения.
--
-- Идемпотентно: INSERT IGNORE по UNIQUE (clinic_id, lab_test_id); уже
-- существующие строки (в т.ч. с ценой) не трогаются. Клиники и анализы — по slug.
-- ═══════════════════════════════════════════════════════════════════════════

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_mojlab_labs;
CREATE TEMPORARY TABLE tmp_mojlab_labs (
	slug VARCHAR(280) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY
);
INSERT INTO tmp_mojlab_labs VALUES
('moj-lab-laboratorija-podgorica-moskovska'),
('moj-lab-laboratorija-city-kvart'),
('moj-lab-laboratorija-budva'),
('moj-lab-laboratorija-ulcinj'),
('moj-lab-laboratorija-cetinje'),
('moj-lab-laboratorija-herceg-novi'),
('moj-lab-laboratorija-kotor'),
('moj-lab-laboratorija-niksic'),
('moj-lab-laboratorija-tivat');

DROP TEMPORARY TABLE IF EXISTS tmp_mojlab_tests;
CREATE TEMPORARY TABLE tmp_mojlab_tests (
	slug VARCHAR(280) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY,
	source_name VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
);
-- (lab_tests.slug, дословная строка сайта; несколько строк сайта — через « ; »)
INSERT INTO tmp_mojlab_tests VALUES
('17-hydroxyprogesterone', '17 OH Progesteron'),
('17-ketosteroids', '17 Ketosteroidi'),
('5-hiaa', '5-HIAA'),
('ace', 'ACE'),
('acetylcholine-receptor-antibodies', 'Anti acetilholin receptor'),
('acth', 'ACTH'),
('activated-partial-thromboplastin-time', 'aPTT'),
('acylcarnitine-profile', 'Acilkarnitin'),
('adalimumab-antibodies', 'Adalimumab antitijela'),
('adalimumab-level', 'Adalimumab (Humira)'),
('adenovirus-iga', 'Anti Adenovirus IgA'),
('adenovirus-igg', 'Anti Adenovirus IgG'),
('adenovirus-respiratory-test', 'Adeno respiratorni virus (bris nosa) (imunohromatografija)'),
('adenovirus-rotavirus-in-stool', 'Rota/Adeno virus (imunohromatografija)'),
('adrenal-antibodies', 'Anti adrenalna antitijela'),
('afp', 'AFP'),
('albumin', 'Albumin'),
('aldolase', 'Aldolaza'),
('aldosterone', 'Aldosteron'),
('alkaline-phosphatase', 'Alkalna fosfataza (ALP)'),
('alkaline-phosphatase-isoenzymes', 'Izoenzimi alkalne fosfataze'),
('alpha-1-antitrypsin', 'Alfa 1 antitripsin'),
('alpha-1-antitrypsin-genotyping', 'Alfa 1 antitripsin deficijencija'),
('alpha-1-microglobulin', 'Alfa 1 mikroglobulin'),
('alt', 'ALT'),
('aluminum', 'Aluminijum'),
('ama-antimitochondrial-m2', 'Ant AMA-M2 antitijela'),
('amine-test', 'Aminski test'),
('amphetamine', 'Amfetamin'),
('amylase', 'Amilaza'),
('amylase-in-urine', 'Urin - Amilaza'),
('ana-antinuclear-antibodies', 'ANA'),
('ana-hep-2', 'ANA (IFA metoda)'),
('anca-c-anti-pr3', 'Anti PR3 (cANCA)'),
('anca-p-anti-mpo', 'Anti MPO (pANCA)'),
('androstenedione', 'Androstenedion'),
('anti-ccp-antibodies', 'Anti-CCP (hs)'),
('anti-hbc-total-elisa', 'HBc antitijela'),
('anti-hbe-elisa', 'Hepatitis B-omotač At'),
('anti-hcv', 'Anti HCV'),
('anti-hcv-antibodies-immunoblot', 'Hepatitis C (Western blot, serum)'),
('anti-heart-antibodies-asa', 'Anti srčana antitijela'),
('anti-insulin-antibodies', 'Anti insulinska IgG'),
('anti-jo-1-antibodies', 'Anti Jo-1 antitijela'),
('anti-la-ssb-antibodies', 'Anti SS-B At'),
('anti-mullerian-hormone', 'AMH'),
('anti-parietal-cell-antibodies-apa', 'Anti H+/K+-ATPaza (parijetalna) antitijela'),
('anti-ro-ssa-antibodies', 'Anti SS-A At'),
('anti-scl-70-antibodies', 'Anti Scl-70'),
('anti-smooth-muscle-antibodies-asma', 'Anti ASMA'),
('anti-thyroglobulin-antibodies', 'TgAt'),
('anti-tpo', 'TPOAt'),
('anti-tshr', 'TSH-R At'),
('anticardiolipin-igg', 'Anti kardiolipinska IgG'),
('anticardiolipin-igm', 'Anti kardiolipinska IgM'),
('antimycogram', 'Antimikogram'),
('antithrombin-iii', 'Antitrobin III'),
('apcr-resistance-to-activated-protein-c', 'APCR (rezistencija na aktivni protein C)'),
('asca-iga', 'Anti ASCA IgA'),
('asca-igg', 'Anti ASCA IgG'),
('ast', 'AST'),
('asto', 'ASTO'),
('barbiturates', 'Barbiturati'),
('benzodiazepines', 'Benzodiazepin'),
('beta-2-glycoprotein-i-igg', 'Anti beta-2-glikoproteinska I IgG'),
('beta-2-glycoprotein-i-igm', 'Anti beta-2-glikoproteinska I IgM'),
('beta-2-microglobulin', 'B2 mikroglobulin'),
('beta-2-microglobulin-in-urine', 'B2 mikroglobulin urin'),
('beta-crosslaps', 'Beta cross laps'),
('bioavailable-testosterone', 'Biodostupni testosteron'),
('bk-virus-pcr', 'BK virus DNK'),
('bleeding-time', 'Vrijeme krvarenja'),
('blood-culture', 'Hemokultura'),
('bordetella-pertussis-pcr', 'Bordetella pertussis DNK'),
('borrelia-burgdorferi-igg', 'Anti Borrelia burgdorferi IgG'),
('borrelia-burgdorferi-igg-western-blot', 'Borrelia IgG, imunoblot'),
('borrelia-burgdorferi-igm', 'Anti Borrelia burgdorferi IgM'),
('borrelia-burgdorferi-igm-western-blot', 'Borrelia IgM, imunoblot'),
('brca1-brca2-genetic-test', 'BRCA1/BRCA2 (genetika karcinoma)'),
('breast-swab-bacteria', 'Bris dojke na bakterije'),
('breast-swab-fungi', 'Bris dojke na gljivice'),
('brucella-igg-elisa', 'Brucella IgG'),
('brucella-igm', 'Brucella IgM'),
('c-peptide', 'C-peptid'),
('c-peptide-in-urine', 'C-peptid u urinu'),
('c-reactive-protein', 'CRP'),
('c3-complement', 'C3'),
('c4-complement', 'C4'),
('ca-125', 'CA 125'),
('ca-15-3', 'CA15-3'),
('ca-19-9', 'CA 19-9'),
('ca-72-4', 'Ca 72-4'),
('calcitonin', 'Kalcitonin'),
('calcium', 'Kalcijum ukupni'),
('calcium-in-urine', 'Urin - Kalcijum'),
('carbamazepine-level', 'Karbamazepin (Tegretol)'),
('carnitine-acylcarnitine-profile', 'Karnitin, acilkarnitin'),
('cea', 'CEA'),
('centromere-protein-b-antibodies', 'Anti centromerna B antitijela'),
('ceruloplasmin', 'Ceruloplazmin'),
('cervical-swab-bacteria', 'Cervikalni bris na bakterije'),
('cervical-swab-fungi', 'Cervikalni bris na gljivice'),
('chitotriosidase', 'Hitotriozidaza'),
('chlamydia-pneumoniae-igg', 'Anti Chlamydia pneumoniae IgG'),
('chlamydia-pneumoniae-igm', 'Anti Chlamydia pneumoniae IgM'),
('chlamydia-trachomatis-igg', 'Chlamydia trachomatis IgG'),
('chlamydia-trachomatis-iht', 'Chlamydia trachomatis (imnohromatografija)'),
('chloride', 'Hloridi'),
('cholesterol', 'Holesterol'),
('chromogranin-a', 'Hromogranin A'),
('ck', 'CK'),
('ck-mb', 'CKMB aktivnost'),
('cmv-avidity', 'CMV IgG aviditet'),
('coagulation-factor-v', 'Faktor V'),
('coagulation-factor-viii', 'Faktor VIII'),
('coagulation-factor-xiii', 'Faktor XIII'),
('coagulation-time', 'Vrijem koagulacije'),
('cocaine', 'Kokain'),
('coenzyme-q10', 'Koenzim Q10'),
('cold-agglutinins', 'Hladni aglutinini'),
('complete-blood-count', 'Krvna slika'),
('copper-in-24h-urine', 'Bakar u 24h urinu'),
('cortisol', 'Kortizol'),
('cortisol-in-urine', 'Kortizol u urinu'),
('covid-19-antigen-test', 'Sars-Cov-2 antigen test (brzi test)'),
('creatinine-clearance', 'Kreatin klirens'),
('creatinine-in-urine', 'Urin - Kreatinin'),
('cryoglobulins', 'Krioglobulini'),
('cyfra-21-1', 'Cyfra 21-1'),
('cystatin-c', 'Cistatin C'),
('cysticercosis-igg', 'Cysticercosis'),
('cystine-in-24h-urine', 'Cistin u 24h urinu'),
('cytomegalovirus-igg', 'Cytomegalo virus IgG'),
('cytomegalovirus-igm', 'Cytomegalo virus IgM'),
('d-dimer', 'D-dimer'),
('demodex-species', 'Demodex (mikroskopski preparat)'),
('dermatomycosis-nmp', 'Dermatomikoze (nokti,dlaka,koza) NMP'),
('dermatophytes-culture', 'Dermatophiti (mikoloska kultura)'),
('dermatophytes-hair-scraping', 'Korjen dlake - nativni preparat'),
('dhea-s', 'DHEAS'),
('digoxin-level', 'Digoxin'),
('dihydrotestosterone', 'Dihidrotestosteron'),
('direct-bilirubin', 'Bilirubin direktni'),
('double-test', 'Double test'),
('drug-panel-5-new', 'Panel 5 (kokain, amfetamin, kanabinoidi, ekstazi, opijati)'),
('dsdna-igg-antibodies', 'Anti dsDNA IgG'),
('duchenne-muscular-dystrophy', 'Duchenne mišićna distrofija (skrining na nasledne bolesti)'),
('ear-swab-bacteria', 'Bris uha na bakterije'),
('ear-swab-fungi', 'Bris uha na gljivice'),
('echinococcus-igg-elisa', 'Anti Echinococcus IgG'),
('ecp-eosinophil-cationic-protein', 'Eozinofilni kationski protein (ECP)'),
('ecstasy', 'Ekstazi'),
('endomysial-iga-antibodies', 'Anti endomizijalna IgA'),
('epstein-barr-ebna-igg', 'EBV EBNA IgG'),
('epstein-barr-igg', 'EBV VCA IgG'),
('epstein-barr-igm', 'EBV VCA IgM'),
('erythrocyte-resistance', 'Osmotska rezistencija eritrocita'),
('erythrocyte-sedimentation-rate', 'Sedimentacija'),
('erythrocytes', 'Eritociti'),
('erythropoietin', 'Eritropoetin'),
('estradiol', 'Estradiol'),
('eye-swab-bacteria', 'Bris oka na bakterije ; Bris konjuktive na bakterije'),
('eye-swab-fungi', 'Bris oka na gljivice ; Bris konjuktive na gljivice'),
('factor-v-leiden-locus-1691', 'Mutacija gena Faktor V Leiden (G1691A) ; Faktor V Leiden (G1691A)'),
('ferritin', 'Feritin'),
('fibrinogen', 'Fibrinogen'),
('folic-acid', 'Folati u serumu'),
('food-allergy-panel-30-allergens', 'Nutritivni panel 30 alergena'),
('food-intolerance-108-panel', 'Intolerancija - 108 namirnica'),
('fragile-x-syndrome-gene-analysis', 'Fragilni X hromozom (skrining na nasledne bolesti)'),
('free-psa', 'PSA, slobodni'),
('free-t3', 'T3 slobodni'),
('free-t4', 'T4 slobodni'),
('free-testosterone', 'Slobodni testosteron'),
('fructosamine', 'Fruktozamin'),
('fsh', 'FSH'),
('gamma-gt', 'GGT'),
('gbm-antibodies', 'Antitijela na glomerularnu bazalnu membranu (GBM)'),
('gbs-culture', 'Kultura na Streptococcus gr. B (GBS)'),
('glans-swab-bacteria', 'Bris glansa na bakterije'),
('glans-swab-fungi', 'Bris glansa na gljivice'),
('gliadin-iga-antibodies', 'Anti glijadinska IgA'),
('gliadin-igg-antibodies', 'Anti glijadinska IgG'),
('glucose', 'Glukoza'),
('gonococcus-iht', 'Neisseria gonorrhoeae (imunohromatografija)'),
('hair-swab-fungi', 'Korijen dlake na gljivice'),
('haptoglobin', 'Haptoglobin'),
('hav-igm', 'Anti HAV IgM'),
('hba1c', 'HbA1c'),
('hbeag', 'Hepatitis B-omotač Ag'),
('hbsab', 'Hepatitis B-površinska At'),
('hbsag', 'HBSAg'),
('hcv-pcr-rna-qualitative', 'Hepatitis C PCR kvalitativno'),
('hcv-rna-genotyping', 'Hepatitis C RNK tipizacija'),
('hdl-cholesterol', 'HDL holesterol'),
('he4', 'HE4'),
('helicobacter-pylori-antigen-in-feces', 'Helicobacter pylori Ag (imunohromatografija)'),
('helicobacter-pylori-iga', 'Anti Helicobacter pylori IgA'),
('helicobacter-pylori-igg', 'Anti Helicobacter pylori IgG'),
('hemoglobin-electrophoresis', 'Elektroforeza hemoglobina'),
('heparin-anti-xa-activity', 'LMW Heparin (anti Xa aktivnost)'),
('herpes-simplex-i-igg', 'HSV 1 IgG'),
('herpes-simplex-i-igm', 'HSV 1 IgM'),
('herpes-simplex-ii-igg', 'HSV 2 IgG'),
('herpes-simplex-ii-igm', 'HSV 2 IgM'),
('histopathology-bilateral-testis-biopsies', 'Obostrana biopsija testisa'),
('histopathology-brain-tumor-examination', 'Pregled tumora mozga'),
('histopathology-bronchoscopic-biopsy', 'Bronhoskopska biopsija'),
('histopathology-cervical-biopsy', 'Biopsija grlića materice'),
('histopathology-cervical-biopsy-and-curettage', 'Biopsija grlića materice i kiretaža'),
('histopathology-cervical-polyp-examination', 'Pregled polipa grlića'),
('histopathology-colon-biopsy', 'Biopsija debelog crijeva'),
('histopathology-conization-specimen', 'Pregled konizata'),
('histopathology-conization-specimen-with-curettage', 'Pregled konizata sa kiretažom'),
('histopathology-consultation', 'Ph konsultacija'),
('histopathology-curettage', 'Kiretaža'),
('histopathology-cytology-smear', 'Citološki pregled - razmaz'),
('histopathology-duodenum-biopsy', 'Biopsija duodenuma'),
('histopathology-endoscopic-biopsy', 'Endoskopski uzeta biopsija'),
('histopathology-fractional-curettage-two-samples', 'Frakciona kiretaža dva uzorka'),
('histopathology-larynx-biopsy', 'Biopsija larinksa'),
('histopathology-liver-biopsy', 'Biopsija jetre'),
('histopathology-lung-tumor-examination', 'Pregled tumora pluća'),
('histopathology-lymph-node-examination', 'Biopsija limfnog čvora'),
('histopathology-mediastinum-biopsy', 'Biopsija medijastinuma'),
('histopathology-multiple-biopsy', 'Multipla biopsija'),
('histopathology-needle-biopsy-liver-lung-kidney', 'Iglena biopsija (jetra, pluća, bubreg)'),
('histopathology-needle-breast-biopsy-without-ihc', 'Iglena biopsija dojke bez imunohistohemije'),
('histopathology-needle-prostate-biopsy', 'Iglena biopsija prostata'),
('histopathology-needle-prostate-biopsy-multiple-samples', 'Iglena biopsija prostate više uzoraka'),
('histopathology-oral-cavity-biopsy', 'Biopsija usne duplje'),
('histopathology-orchiectomy-testis-examination', 'Pregled orhiektomije'),
('histopathology-other-biopsies', 'Ostale biopsije'),
('histopathology-pleura-biopsy', 'Biopsija pleure'),
('histopathology-radical-surgery', 'Ph radikalne operacije'),
('histopathology-removed-breast-examination', 'Pregled odstranjene dojke'),
('histopathology-report-review', 'Revizija biopsije'),
('histopathology-skin-tumor-additional-samples-15', 'Biopsija tumora kože svaki sledeći uzorak'),
('histopathology-standard-diagnostics', 'Ph standardna dijagnostika'),
('histopathology-subcutaneous-tumor-examination', 'Pregled potkožnog tumora'),
('histopathology-surgical-breast-biopsy-without-ihc', 'Klinoidna biopsija dojke bez imunohistohemije'),
('histopathology-testis-biopsy', 'Biopsija testisa'),
('histopathology-thyroid-biopsy', 'Biopsija štitne žlijezde'),
('histopathology-trus-prostate', 'TRUS prostate'),
('histopathology-uterus-examination', 'Pregled uterusa'),
('histopathology-vulvar-biopsy', 'Biopsija vulve'),
('hiv-1-plus-2-ag-ab', 'HIV 1+2 ( Ag/At)'),
('hla-b27', 'HLA-B27'),
('homocysteine', 'Homocistein'),
('hpv-14-types-pcr', 'HPV genotipizacija - visokorizične (16,18,31,33,35,39,45,51,52,56,58,59,66,68)'),
('human-herpesvirus-6-pcr', 'Herpes tip 6 DNK'),
('ia-2-antibodies', 'Anti IA2 (tirozin fosfataza) antitijela'),
('ica-antibodies', 'Anti ICA (pankreasna ostrvca) antitijela'),
('iga', 'IgA'),
('ige', 'IgE'),
('igf-1', 'IgF1'),
('igg', 'IgG'),
('igg-subclasses', 'IgG potklase (IgG1, IgG2, IgG3, IgG4)'),
('igm', 'IgM'),
('immunohistochemistry-5-to-10-antibodies', 'Imunohistohemijska analiza 5 do 10 antitijela'),
('immunohistochemistry-more-than-10-antibodies', 'Imunohistohemijska analiza više od 10 antitijela'),
('immunohistochemistry-per-antibody', 'Imunohistohemijska analiza po jednom antitijelu'),
('infliximab-antibodies', 'Infliximab antitjela'),
('infliximab-level', 'Infliximab (Remicade)'),
('influenza-a-plus-b-iht', 'Influenza A/B (imunohromatografija)'),
('influenza-b-virus-igg-elisa', 'Influenca B IgG'),
('inhalant-allergy-panel-30-allergens', 'Inhalatorni panel 30 alergena'),
('inhibin-b', 'Inhibin B'),
('insulin', 'Insulin'),
('interleukin-6', 'Interleukin 6'),
('intrinsic-factor-antibodies', 'Anti intrinzični faktor antitijela'),
('ionized-calcium', 'Kalcijum slobodni (jonizovani)'),
('iron', 'Gvožđe'),
('karyotype', 'Kariotip'),
('lactose-intolerance-pcr', 'Intolerancija na laktozu'),
('lamotrigine-level', 'Lamictal (Lamotrigine)'),
('ldh', 'LDH'),
('ldl-cholesterol', 'LDL holesterol'),
('legionella-pneumophila-igg', 'Legionella pneum. IgG'),
('legionella-pneumophila-igm', 'Legionella pneum. IgM'),
('leukocytes', 'Leukociti'),
('levetiracetam-level', 'Levitiracetam (Kepra)'),
('lh', 'LH'),
('lipase', 'Lipaza'),
('lipoprotein-a', 'Lp (a)'),
('lithium', 'Litijum'),
('lupus-anticoagulant', 'LA (LA 1/ LA2)'),
('macroprolactin', 'Makroprolaktin'),
('magnesium', 'Magnezijum'),
('magnesium-in-urine', 'Urin - Magnezijum'),
('marijuana', 'Kanabinoidi'),
('measles-igg', 'Anti Measles IgG'),
('measles-igm', 'Anti Measles IgM'),
('melatonin', 'Melatonin'),
('metanephrines-in-urine', 'Metanefrini u urinu'),
('methadone', 'Metadon'),
('methamphetamine', 'Metamfetamin'),
('methylmalonic-acid', 'Metilmalonska kisjelina'),
('microalbumin-in-urine', 'Urin - Albumin'),
('mog-myelin-oligodendrocyte-glycoprotein', 'Anti MOG (mijelin-oligodendrocitni glikoprotein) IgG'),
('monosticon', 'Monostikon test'),
('mthfr-locus-1298', 'MTHFR A1298C ; Mutacija gena MTHFR (A1298C)'),
('mthfr-locus-677-pcr', 'MTHFR C677T ; Mutacija gena MTHFR (C677T)'),
('mumps-igg', 'Anti Mumps IgG'),
('mumps-igm', 'Anti Mumps IgM'),
('mycoplasma-hominis-genitalium-pcr', 'Mycoplasma panel (Mycoplasma hominis, Mycoplasma genitalium'),
('mycoplasma-hominis-ureaplasma', 'Mycoplasma hominis/Ureaplasma urealyticum (kultura sa antibiogramom)'),
('mycoplasma-pneumoniae-iga', 'Mycoplasma pneumoniae IgA'),
('mycoplasma-pneumoniae-igg', 'Mycoplasma pneumoniae IgG'),
('nail-swab-fungi', 'Bris nokta na gljivice'),
('needle-breast-biopsy-with-her2-and-ki67-receptors', 'Iglena biopsija dojke sa određivanjem steroidnih receptora, Her2 i Ki67'),
('neisseria-gonorrhoeae-culture', 'Neisseria gonorrhoeae (kultura)'),
('norovirus-in-stool', 'Noro virus (imunohromatografija)'),
('nose-swab-bacteria', 'Bris nosa na bakterije'),
('nose-swab-fungi', 'Bris nosa na glivice'),
('nse', 'NSE'),
('nt-probnp', 'NT-ProBNP'),
('opiates', 'Opijati'),
('oral-cavity-fungi', 'Bris usne duplje na gljivice'),
('oral-cavity-swab-bacteria', 'Bris usne duplje na bakterije'),
('oral-glucose-tolerance-test', 'OGTT'),
('osteocalcin', 'Osteokalcin'),
('oxcarbazepine-level', 'Oksikarbazepin'),
('pai-1-675-4g-5g', 'Mutacija gena PAI-1 4G/5G'),
('pancreatic-amylase', 'Pankreasna amilaza'),
('pap-papanicolaou-test', 'PAPA test'),
('parvovirus-b19-igg', 'Anti Parvovirus B19 IgG'),
('parvovirus-b19-igm', 'Anti Parvovirus B19 IgM'),
('pediatric-allergy-panel-30-allergens', 'Pedijatrijski panel 30 alergena'),
('perianal-impression', 'Perianalni otisak'),
('phenobarbital-level', 'Fenobarbiton'),
('phospholipid-igg-antibodies', 'Anti fosfolipidna IgG'),
('phospholipid-igm-antibodies', 'Anti fosfolipidna IgM'),
('phosphorus', 'Fosfati'),
('phosphorus-in-urine', 'Urin - Fosfati'),
('platelet-count-microscopic', 'Trombociti u komori'),
('platelets', 'Trombociti'),
('porphobilinogen', 'Porfobilinogen'),
('potassium', 'Kalijum'),
('prepuce-swab-bacteria', 'Bris prepucijuma na bakterije'),
('prepuce-swab-fungi', 'Bris prepucijuma na gljivice'),
('procalcitonin', 'Prokalcitonin'),
('progesterone', 'Progesteron'),
('prolactin', 'Prolaktin'),
('protein-c', 'Protein C (akt)'),
('protein-electrophoresis-serum', 'Elektroforeza proteina seruma'),
('protein-electrophoresis-urine', 'Elektroforeza proteina urina'),
('protein-in-urine', 'Urin - Proteini'),
('protein-s', 'Protein S (akt)'),
('protein-s-100', 'S-100'),
('prothrombin-ii-locus-20210-pcr', 'Mutacija gena Faktor II protrombin (G20210A) ; Faktor II protrombin (G20210A)'),
('prothrombin-time-pt-inr', 'Protrombinsko vrijeme ; INR'),
('protozoa-stool-test', 'Ag Protozoa (Cryptosporidium, Giardia i Entamoeba)'),
('psa', 'PSA, ukupni'),
('pth', 'PTH'),
('punctate-aerobic', 'Punktat na bakterije'),
('punctate-fungi', 'Punktat na gljivice'),
('pyruvate', 'Piruvati'),
('quantiferon', 'IGRA-TB (komercijalni naziv drugih testova Quantiferon)'),
('rapid-strep-a', 'Streptococcus Pyogenes Ag (brzi test)'),
('removed-breast-and-axillary-lymph-nodes-examination', 'Pregled odstranjene dojke sa aksilarnim limfnim čvorovima'),
('removed-breast-with-her2-and-ki67-receptors', 'Pregled odstranjene dojke sa sa određivanjem steroidnih receptora, Her2 i Ki67'),
('reticulocytes', 'Retikulociti'),
('rheumatoid-factor', 'Reuma faktor'),
('roma-index', 'Roma index'),
('rubella-igg', 'Anti Rubella IgG'),
('rubella-igm', 'Anti Rubella IgM'),
('sars-cov-2-igg-spike-protein', 'Sars-Cov-2 IgG - Spike (Clia)'),
('sars-cov-2-igm', 'Sars-Cov-2 IgM (Clia)'),
('sars-cov-2-pcr', 'SARS-Cov2 (RT-PCR)'),
('scc-squamous-cell-carcinoma-antigen', 'SCC'),
('selenium', 'Selen'),
('serotonin', 'Serotonin'),
('serum-osmolality', 'Osmolalnost seuma'),
('shbg', 'SHBG'),
('skin-swab-bacteria', 'Bris kože na bakterije'),
('skin-swab-fungi', 'Bris kože na gljivice'),
('sma-smn1-gene-copy-number', 'Spinalna mišićna atrofija (skrining na nasledne bolesti)'),
('sodium', 'Natrijum'),
('sperm-culture-bacteria', 'Spermokultura'),
('sperm-culture-fungi', 'Spermokultura na gljivice'),
('sputum-bacteria', 'Sputum na bakterije'),
('sputum-fungi', 'Sputum na gljivice'),
('std-multiplex-3', 'STD panel manji (Trichomonas vaginalis, Neisseria gonorrhoeae, Chlamydia trachomatis)'),
('stool-fungi', 'Stolica na gljivice'),
('stool-parasites', 'Stolica na parazite'),
('surgical-breast-biopsy-with-her2-and-ki67-receptors', 'Klinoidna biopsija dojke sa određivanjem steroidnih receptora, Her2 i Ki67'),
('t3', 'T3 ukupni'),
('t4', 'T4 ukupni'),
('tacrolimus-level', 'Tacrolimus'),
('testosterone', 'Testosteron'),
('throat-swab-bacteria', 'Bris grla na bakterije'),
('throat-swab-fungi', 'Bris grla na gljivice'),
('thrombin-time', 'Trombinsko vrijeme'),
('thyroglobulin', 'Tireoglobulin'),
('tibc', 'TIBC'),
('tongue-swab-bacteria', 'Bris jezika na bakterije'),
('tongue-swab-fungi', 'Bris jezika na gljivice'),
('torch-panel', 'TORCH'),
('total-bile-acids', 'Žučne kisjeline'),
('total-bilirubin', 'Bilirubin ukupni'),
('total-protein', 'Proteini'),
('total-tau-protein', 'Tau protein'),
('toxoplasma-igg', 'Anti Toxoplasma IgG'),
('toxoplasma-igm', 'Anti Toxoplasma IgM'),
('tpmt-gene-mutation-detection', 'Tiopurin metil transferaza deficijencija'),
('transferrin', 'Transferin'),
('transferrin-saturation', 'Saturacija transferina'),
('transglutaminase-iga-antibodies', 'Anti tkivna transglutaminaza IgA'),
('transglutaminase-igg-antibodies', 'Anti tkivna transglutaminaza IgG'),
('tricyclic-antidepressants', 'TCA (triciklični antidepresivi)'),
('triglycerides', 'Trigliceridi'),
('triple-test-second-trimester-screening', 'Tripl test'),
('troponin-t-hs', 'hs Troponin T'),
('tsh', 'TSH'),
('ugt1a1-gilbert-syndrome', 'UGT1A1 - Gilbertov sindrom'),
('uibc', 'UIBC'),
('umbilicus-swab-bacteria', 'Bris pupka na bakterije'),
('umbilicus-swab-fungi', 'Bris pupka na gljivice'),
('urea', 'Urea'),
('urea-clearance', 'Urea klirens'),
('urea-in-urine', 'Urin - Urea'),
('urethral-swab-bacteria', 'Bris uretre na bakterije'),
('urethral-swab-fungi', 'Bris uretre na gljivice'),
('uric-acid', 'Mokraćna kisjelina'),
('uric-acid-in-urine', 'Urin - Mokraćna kisjelina'),
('urine-culture', 'Urinokultura'),
('urine-fungi', 'Urinokultura na gljivice'),
('urine-osmolality', 'Osmolalnost urina'),
('vaginal-swab-bacteria', 'Bris vagine na bakterije'),
('vaginal-swab-fungi', 'Bris vagine na gljivice'),
('valproic-acid', 'Valproična kisjelina'),
('varicella-zoster-virus-igg', 'Anti Varicella zoster IgG'),
('varicella-zoster-virus-igm', 'Anti Varicella zoster IgM'),
('vdrl', 'VDRL (flokulacioni test)'),
('vitamin-a', 'Vitamin A'),
('vitamin-b1-level', 'Vitamin B1'),
('vitamin-b12', 'Vitamin B12'),
('vitamin-b2', 'Vitamin B2'),
('vitamin-d-25-oh', 'Vitamin D'),
('vitamin-e-level', 'Vitamin E'),
('vitamin-h-b7-biotin-level', 'Vitamin H'),
('vldl', 'VLDL holesterol'),
('vulvar-swab-bacteria', 'Bris vulve na bakterije'),
('vulvar-swab-fungi', 'Bris vulve na gljivice'),
('waaler-rose-test', 'Waller-rose'),
('west-nile-virus-igg-elisa', 'Virus zapadnog Nila IgG'),
('west-nile-virus-igm-elisa', 'Virus zapadnog Nila IgM'),
('wound-swab-bacteria', 'Bris rane na bakterije'),
('wound-swab-culture-anaerobic', 'Bris rane na anaerobne bakterije'),
('wound-swab-fungi', 'Bris rane na gljivice'),
('y-chromosome-microdeletion', 'Mikrodelecija na Y hromozomu'),
('znt8-antibodies', 'Anti Zn transporter antitijela');

-- Контроль: каждый slug анализа должен найтись (ожидается пусто)
SELECT t.slug AS missing_lab_test FROM tmp_mojlab_tests t LEFT JOIN lab_tests lt ON lt.slug = t.slug WHERE lt.id IS NULL;
-- Контроль: все 9 лабораторий должны найтись (ожидается пусто)
SELECT l.slug AS missing_clinic FROM tmp_mojlab_labs l LEFT JOIN clinics c ON c.slug = l.slug WHERE c.id IS NULL;

INSERT IGNORE INTO clinic_lab_tests (clinic_id, lab_test_id, price)
SELECT c.id, lt.id, NULL
FROM tmp_mojlab_labs l
JOIN clinics c ON c.slug = l.slug
CROSS JOIN tmp_mojlab_tests t
JOIN lab_tests lt ON lt.slug = t.slug;

DROP TEMPORARY TABLE tmp_mojlab_tests;
DROP TEMPORARY TABLE tmp_mojlab_labs;

COMMIT;

-- ═══ VERIFICATION: у каждой из 9 лабораторий 453 анализов, with_price = 0 ═══
SELECT c.slug, COUNT(clt.id) AS lab_tests, SUM(clt.price IS NOT NULL) AS with_price
FROM clinics c
LEFT JOIN clinic_lab_tests clt ON clt.clinic_id = c.id
WHERE c.slug LIKE 'moj-lab-laboratorija-%'
GROUP BY c.slug
ORDER BY c.slug;
