-- Migration: FZOCG tariffs — PDF verification pass (2026-06-11), INCREMENTAL
-- Applies ONLY the rows that actually changed vs the production state (git 9e93b20).
-- The full insert-tariff-fzocg-*.sql snapshots already match FINAL.json and are for
-- fresh environments — do NOT re-run them on the live DB; run only this file.
--
-- Scope: substantive fixes only (prices, added/removed rows, real name errors).
-- Pure-diacritic renames and section labels on pre-existing rows are intentionally
-- skipped (never a flagged problem; they live in FINAL.json for the next full sync).
--
-- Run: mysql -u <user> -p --default-character-set=utf8mb4 docta_me < server/sql/update-tariff-fzocg-2026-06-11-verify.sql
-- Then relink:  update-medical-service-tariffs-linkage.sql  +  -name-match.sql

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET CHARACTER SET utf8mb4;

-- ── fzocg-pzz : 0 update, 1 insert, 0 delete ──
INSERT INTO `medical_service_tariffs` (`tariff_source`, `code`, `scheme`, `price_eur`, `price_odjeljenje_eur`, `price_ambulanta_eur`, `price_operacija_eur`, `price_anestezija_eur`, `price_ukupno_eur`, `coefficient`, `base_coefficient_eur`, `name_sr_latin`, `section`, `subsection`, `amended_from`, `effective_from`, `source_signed_number`, `source_pdf`, `notes`) VALUES
('fzocg-pzz', 'X01022-JZP', 'single', 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Direktno opservirana terapija za TBC (DOTs)', 'Jedinica za patronažu', NULL, NULL, '2026-05-01', NULL, 'Cjenovnik-zdravstvenih-usluga-na-primarnom-nivou-zdravstvene-zastite-PZZ-od-01.05.2026.pdf', 'Izvorni kod: X01022 (sekcija: Jedinica za patronažu). Kod izmijenjen u X01022-JZP radi jedinstvenosti (isti kod postoji u drugoj sekciji).')
ON DUPLICATE KEY UPDATE `scheme` = VALUES(`scheme`), `price_eur` = VALUES(`price_eur`), `price_odjeljenje_eur` = VALUES(`price_odjeljenje_eur`), `price_ambulanta_eur` = VALUES(`price_ambulanta_eur`), `price_operacija_eur` = VALUES(`price_operacija_eur`), `price_anestezija_eur` = VALUES(`price_anestezija_eur`), `price_ukupno_eur` = VALUES(`price_ukupno_eur`), `coefficient` = VALUES(`coefficient`), `base_coefficient_eur` = VALUES(`base_coefficient_eur`), `name_sr_latin` = VALUES(`name_sr_latin`), `section` = VALUES(`section`), `subsection` = VALUES(`subsection`), `amended_from` = VALUES(`amended_from`), `effective_from` = VALUES(`effective_from`), `source_signed_number` = VALUES(`source_signed_number`), `source_pdf` = VALUES(`source_pdf`), `notes` = VALUES(`notes`);

-- ── fzocg-sekundarna : 3 update, 0 insert, 0 delete ──
UPDATE `medical_service_tariffs` SET `scheme` = 'operacija', `price_eur` = NULL, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = 325.0, `price_anestezija_eur` = 65.0, `price_ukupno_eur` = 390.0, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Desna lobektomija jetre-laparoskopska op.', `section` = '36. OPERACIJE - HIRURGIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-07-29', `source_signed_number` = '01-4596', `source_pdf` = '15846071842.-Cjenovnik-zdravstvenih-usluga-na-sekundarnom-i.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-sekundarna' AND `code` = 'D02241';
UPDATE `medical_service_tariffs` SET `scheme` = 'operacija', `price_eur` = NULL, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = 130.0, `price_anestezija_eur` = 26.0, `price_ukupno_eur` = 156.0, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Izvođenje derivacione stome kolona bez resekcije', `section` = '36. OPERACIJE - HIRURGIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-07-29', `source_signed_number` = '01-4596', `source_pdf` = '15846071842.-Cjenovnik-zdravstvenih-usluga-na-sekundarnom-i.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-sekundarna' AND `code` = 'D02252';
UPDATE `medical_service_tariffs` SET `scheme` = 'operacija', `price_eur` = NULL, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = 32.5, `price_anestezija_eur` = 9.1, `price_ukupno_eur` = 41.6, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Fraktura distalne epifize radiusa-otvorena i zatvorena, manipulativna repozicija', `section` = '48. OPERACIJE - ORTOPEDIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-07-29', `source_signed_number` = '01-4596', `source_pdf` = '15846071842.-Cjenovnik-zdravstvenih-usluga-na-sekundarnom-i.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-sekundarna' AND `code` = 'D05065';

-- ── fzocg-drg : 1 update, 0 insert, 3 delete ──
DELETE FROM `medical_service_tariffs` WHERE `tariff_source` = 'fzocg-drg' AND `code` = 'I22Z';
DELETE FROM `medical_service_tariffs` WHERE `tariff_source` = 'fzocg-drg' AND `code` = 'I25Z';
DELETE FROM `medical_service_tariffs` WHERE `tariff_source` = 'fzocg-drg' AND `code` = 'O65Z';
UPDATE `medical_service_tariffs` SET `scheme` = 'coefficient', `price_eur` = 1064.25, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = 1.4, `base_coefficient_eur` = 760.18, `name_sr_latin` = 'Dijagnostičke procedure na kostima i zglobovima uključujući biopsiju bez KK', `section` = 'MDC 08', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2025-01-01', `source_signed_number` = '01-11057', `source_pdf` = 'Cjenovnik-zdravstvenih-usluga-po-DRG-od-01.01.2025.g.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-drg' AND `code` = 'I25B';

-- ── fzocg-transfuziologija : 3 update, 0 insert, 0 delete ──
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 23.86, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Eluciona tehnika', `section` = 'INTERVENCIJE I PROCEDURE TRANSFUZIOLOGIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-05-21', `source_signed_number` = '01-2751', `source_pdf` = '162758924911.-Cjenovnik-zdravstvenih-usluga-transfuziologije.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-transfuziologija' AND `code` = 'X12021';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 13.34, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Izdvajanje plazme', `section` = 'INTERVENCIJE I PROCEDURE TRANSFUZIOLOGIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-05-21', `source_signed_number` = '01-2751', `source_pdf` = '162758924911.-Cjenovnik-zdravstvenih-usluga-transfuziologije.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-transfuziologija' AND `code` = 'X12060';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 5.83, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Zbrinjavanje kolapsa kod davaoca, trudnice', `section` = 'PREGLEDI I ADMINISTRACIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-05-21', `source_signed_number` = '01-2751', `source_pdf` = '162758924911.-Cjenovnik-zdravstvenih-usluga-transfuziologije.pdf', `notes` = NULL WHERE `tariff_source` = 'fzocg-transfuziologija' AND `code` = 'G05005';

-- ── fzocg-apotekarska : 1 update, 3 insert, 0 delete ──
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 1.08, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Miješanje hidrogena sa vodom do 100g', `section` = 'RADNE TAKSE', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2015-01-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-apotekarska' AND `code` = '606';
INSERT INTO `medical_service_tariffs` (`tariff_source`, `code`, `scheme`, `price_eur`, `price_odjeljenje_eur`, `price_ambulanta_eur`, `price_operacija_eur`, `price_anestezija_eur`, `price_ukupno_eur`, `coefficient`, `base_coefficient_eur`, `name_sr_latin`, `section`, `subsection`, `amended_from`, `effective_from`, `source_signed_number`, `source_pdf`, `notes`) VALUES
('fzocg-apotekarska', '1', 'single', 0.83, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rastvaranje antibiotskih sirupa', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL),
('fzocg-apotekarska', '50-RT', 'single', 0.64, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mjerenje jedne supstance do 1000 g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, 'Izvorni kod: 50 (sekcija: RADNE TAKSE). Kod izmijenjen u 50-RT radi jedinstvenosti (isti kod postoji u drugoj sekciji).'),
('fzocg-apotekarska', '607', 'single', 1.19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Miješanje hidrogena sa vodom do 200g', 'RADNE TAKSE', NULL, NULL, '2015-01-01', NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE `scheme` = VALUES(`scheme`), `price_eur` = VALUES(`price_eur`), `price_odjeljenje_eur` = VALUES(`price_odjeljenje_eur`), `price_ambulanta_eur` = VALUES(`price_ambulanta_eur`), `price_operacija_eur` = VALUES(`price_operacija_eur`), `price_anestezija_eur` = VALUES(`price_anestezija_eur`), `price_ukupno_eur` = VALUES(`price_ukupno_eur`), `coefficient` = VALUES(`coefficient`), `base_coefficient_eur` = VALUES(`base_coefficient_eur`), `name_sr_latin` = VALUES(`name_sr_latin`), `section` = VALUES(`section`), `subsection` = VALUES(`subsection`), `amended_from` = VALUES(`amended_from`), `effective_from` = VALUES(`effective_from`), `source_signed_number` = VALUES(`source_signed_number`), `source_pdf` = VALUES(`source_pdf`), `notes` = VALUES(`notes`);

-- ── fzocg-medicinsko-pomagala : 7 update, 1 insert, 0 delete ──
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 210.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ležište proteze za šaku, mehaničke', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AA1201';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 221.39, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ležište za pasivnu podlakatnu protezu, plastično', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AA1204';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 150.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Zamjena zgloba kuka', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AA2813';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 117.07, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Aparat za Pectus carinatum', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AB3111';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 142.1, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ortopedske cipele za Hallux valgus', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AC1110';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 196.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ortopedske cipele za deformaciju stopala poslije dubokih opekotina', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AC1112';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 171.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ortopedske cipele za Pes plano-varus', `section` = NULL, `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2026-05-01', `source_signed_number` = NULL, `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-medicinsko-pomagala' AND `code` = 'AC1117';
INSERT INTO `medical_service_tariffs` (`tariff_source`, `code`, `scheme`, `price_eur`, `price_odjeljenje_eur`, `price_ambulanta_eur`, `price_operacija_eur`, `price_anestezija_eur`, `price_ukupno_eur`, `coefficient`, `base_coefficient_eur`, `name_sr_latin`, `section`, `subsection`, `amended_from`, `effective_from`, `source_signed_number`, `source_pdf`, `notes`) VALUES
('fzocg-medicinsko-pomagala', 'AA2814', 'single', 150.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Zamjena dezartikulacionog koljena', NULL, NULL, NULL, '2026-05-01', NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE `scheme` = VALUES(`scheme`), `price_eur` = VALUES(`price_eur`), `price_odjeljenje_eur` = VALUES(`price_odjeljenje_eur`), `price_ambulanta_eur` = VALUES(`price_ambulanta_eur`), `price_operacija_eur` = VALUES(`price_operacija_eur`), `price_anestezija_eur` = VALUES(`price_anestezija_eur`), `price_ukupno_eur` = VALUES(`price_ukupno_eur`), `coefficient` = VALUES(`coefficient`), `base_coefficient_eur` = VALUES(`base_coefficient_eur`), `name_sr_latin` = VALUES(`name_sr_latin`), `section` = VALUES(`section`), `subsection` = VALUES(`subsection`), `amended_from` = VALUES(`amended_from`), `effective_from` = VALUES(`effective_from`), `source_signed_number` = VALUES(`source_signed_number`), `source_pdf` = VALUES(`source_pdf`), `notes` = VALUES(`notes`);

-- ── fzocg-van-mreze : 4 update, 0 insert, 0 delete ──
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 80.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'MR pregled lumbosakralne kičme - bez kontrasta', `section` = '2. RADIOLOSKA DIJAGNOSTIKA', `subsection` = NULL, `amended_from` = '2023-12-01', `effective_from` = '2021-09-01', `source_signed_number` = '01-8843', `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-van-mreze' AND `code` = 'J09007';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 107.0, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'MR toraksa/medijastinuma - sa kontrastom', `section` = '2. RADIOLOSKA DIJAGNOSTIKA', `subsection` = NULL, `amended_from` = '2023-12-01', `effective_from` = '2021-09-01', `source_signed_number` = '01-8843', `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-van-mreze' AND `code` = 'J09026';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 291.28, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Laser trabekuloplastika', `section` = '4. OPERACIJE - OFTALMOLOGIJA', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2021-09-01', `source_signed_number` = '01-8843', `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-van-mreze' AND `code` = 'D07012';
UPDATE `medical_service_tariffs` SET `scheme` = 'single', `price_eur` = 16.68, `price_odjeljenje_eur` = NULL, `price_ambulanta_eur` = NULL, `price_operacija_eur` = NULL, `price_anestezija_eur` = NULL, `price_ukupno_eur` = NULL, `coefficient` = NULL, `base_coefficient_eur` = NULL, `name_sr_latin` = 'Ultrazvučni pregled žene', `section` = '9. USLUGE ASISTIRANE REPRODUKCIJE (VANTJELESNE OPLODNJE)', `subsection` = NULL, `amended_from` = NULL, `effective_from` = '2021-09-01', `source_signed_number` = '01-8843', `source_pdf` = NULL, `notes` = NULL WHERE `tariff_source` = 'fzocg-van-mreze' AND `code` = 'X04042';

-- ── Post-checks ──
SELECT `tariff_source`, COUNT(*) AS rows_now FROM `medical_service_tariffs`
GROUP BY `tariff_source` ORDER BY FIELD(`tariff_source`,
  'fzocg-pzz','fzocg-sekundarna','fzocg-drg','fzocg-transfuziologija',
  'fzocg-apotekarska','fzocg-medicinsko-pomagala','fzocg-van-mreze');
-- expect: pzz 493 | sekundarna 4031 | drg 694 | transfuziologija 67 | apotekarska 40 | medicinsko-pomagala 416 | van-mreze 81
SELECT `tariff_source`,`code`,`section`,`price_eur` FROM `medical_service_tariffs`
WHERE (`tariff_source`='fzocg-pzz' AND `code` IN ('X01022','X01022-JZP'))
   OR (`tariff_source`='fzocg-apotekarska' AND `code` IN ('50','50-RT'))
ORDER BY `tariff_source`,`code`;
