import { LanguageId } from '~/enums/language';

/**
 * Слаги всех статей — источник для sitemap.
 *
 * Раньше список жил захардкоженным массивом из ДВУХ слагов прямо в
 * `server/common/sitemap/sitemap.ts`, при 17 статьях в `pages/articles/`.
 * Расхождение было молчаливым и стоило 15 страниц: в индексе Яндекса нашлись
 * ровно те две статьи, что были в sitemap, и ни одной больше — для этого
 * раздела sitemap и есть канал обнаружения, листинг `/articles` не работает.
 * См. prd/silent-200-index-hygiene, итерация 2.
 *
 * Массив явный: страницы статичные, а читать файлы в рантайме Nitro нельзя.
 * За актуальностью следит `tests/unit/article-slugs.spec.ts` — он падает, если
 * список разошёлся с файлами `pages/articles/` или со ссылками на листинге.
 * Добавил статью — допиши слаг сюда.
 */
export const ARTICLE_SLUGS = [
	'allergy-medicines-in-montenegro',
	'birth-in-montenegro',
	'child-healthcare-in-montenegro',
	'clinics-with-language-support',
	'dentistry-in-montenegro',
	'health-insurance-for-residence-permit',
	'healthcare-in-bar',
	'healthcare-in-budva',
	'healthcare-in-kotor',
	'healthcare-in-podgorica',
	'healthcare-system-in-montenegro',
	'lab-tests-and-checkups',
	'medications-not-available-in-montenegro',
	'mental-health-in-montenegro',
	'pharmacies-and-medications',
	'russian-speaking-doctors-in-montenegro',
	'tourist-healthcare-in-montenegro',
	'weekend-medical-help-in-montenegro',
];

// Языки для статьи «Клиники с языковой поддержкой» (без сербского — он по умолчанию).
// Используется и на /articles для подсчёта цифр в мета-строке карточки.
export const CLINIC_SUPPORT_LANGUAGE_IDS = [
	LanguageId.EN,
	LanguageId.RU,
	LanguageId.DE,
	LanguageId.TR,
	LanguageId.IT,
	LanguageId.FR,
];

/**
 * Статьи в глобальном поиске.
 *
 * Поводом стал разрыв: «Zyrtec» в поиске не давал НИЧЕГО, хотя ответ у нас
 * написан — цетиризина в реестре ЧГ нет, и об этом есть статья. Сопоставить
 * бренд с препаратом было нечем: `med_foreign_products` ссылается на
 * `med_substances`, а там только вещества зарегистрированных здесь лекарств.
 * Статьи же из поиска не находились вообще ни по какому запросу.
 *
 * `titleKey` — ключ ЗАГОЛОВКА статьи, того же, что стоит на самой странице и
 * на карточке в списке `/articles`. Сначала здесь были свои короткие ярлыки
 * (`i18n/article-search.ts`), но одна статья в выдаче называлась иначе, чем
 * страница, на которую ведёт, и это читалось как другой материал. Второго
 * названия у статьи быть не должно, поэтому берём заголовок как есть.
 *
 * Заголовки лежат по своим файлам: общие — в `i18n/articles.ts`, у отдельных
 * статей — в их собственных (`UnaTitle`, `AlgTitle`, `WeekendMedicalHelpTitle`,
 * `CityHcTitle_*`). `components/global-search.vue` подмешивает те же словари,
 * что и листинг статей; полноту ключей во всех локалях проверяет
 * tests/unit/article-slugs.spec.ts.
 *
 * `keywords` — то, по чему статью ищут, но чего нет в ярлыке: торговые
 * названия, синонимы, названия городов в другом алфавите. Не локализуются:
 * список плоский, со словами всех языков сразу, потому что он не
 * показывается — по нему только матчатся (сравнение через
 * `normalizeForSearch`, регистр и диакритика неважны). Каждое слово обязано
 * реально встречаться в статье: подпись в выдаче обещает «упоминается».
 */
export interface ArticleSearchEntry {
	slug: string;
	titleKey: string;
	keywords: string[];
}

export const ARTICLE_SEARCH: ArticleSearchEntry[] = [
	{
		slug: 'medications-not-available-in-montenegro',
		titleKey: 'UnaTitle',
		keywords: [
			'zyrtec',
			'зиртек',
			'цетиризин',
			'cetirizin',
			'setirizin',
			'xyzal',
			'ксизал',
			'левоцетиризин',
			'levocetirizin',
			'tavegil',
			'тавегил',
			'клемастин',
			'klemastin',
			'энтеросгель',
			'enterosgel',
			'полисорб',
			'регидрон',
			'мирамистин',
			'miramistin',
			'корвалол',
			'corvalol',
			'валокордин',
			'валидол',
			'пенталгин',
			'панангин',
			'аспаркам',
			'фенистил',
			'фенибут',
			'актовегин',
			'церебролизин',
			'мексидол',
			'милдронат',
			'гептрал',
			'арбидол',
			'кагоцел',
			'циклоферон',
			'цитовир',
			'эргоферон',
			'виферон',
			'полиоксидоний',
			'диоксидин',
			'дротаверин',
			'ввозить',
			'винпоцетин',
			'мебеверин',
			'ozempic',
			'wegovy',
			'mounjaro',
			'семаглутид',
			'тирзепатид',
			'forxiga',
			'форсига',
			'jardiance',
			'джардинс',
			'дапаглифлозин',
			'метформин',
		],
	},
	{
		slug: 'allergy-medicines-in-montenegro',
		titleKey: 'AlgTitle',
		keywords: [
			'аллергия',
			'alergija',
			'алергија',
			'allergie',
			'allergy',
			'alerji',
			'антигистаминные',
			'antihistaminik',
			'пыльца',
			'pollen',
			'polen',
			'полен',
			'zyrtec',
			'зиртек',
			'кларитин',
			'claritine',
			'лоратадин',
			'loratadin',
			'дезлоратадин',
			'aerius',
			'эриус',
			'супрастин',
			'suprastin',
			'фексофенадин',
			'feksofenadin',
			'биластин',
			'bilastin',
			'адреналин',
			'epipen',
			'анафилаксия',
		],
	},
	{
		slug: 'pharmacies-and-medications',
		titleKey: 'PharmaciesTitle',
		keywords: [
			'аптека',
			'apoteka',
			'апотека',
			'apotheke',
			'pharmacy',
			'eczane',
			'рецепт',
			'recept',
			'reçete',
			'rezept',
			'prescription',
		],
	},
	{
		slug: 'birth-in-montenegro',
		titleKey: 'BirthInMontenegroTitle',
		keywords: [
			'роды',
			'роддом',
			'беременность',
			'porod',
			'porođaj',
			'породилиште',
			'geburt',
			'schwangerschaft',
			'birth',
			'pregnancy',
			'doğum',
			'gebelik',
			'акушер',
			'кесарево',
			'эпидуральная',
		],
	},
	{
		slug: 'health-insurance-for-residence-permit',
		titleKey: 'ResidenceInsuranceTitle',
		keywords: [
			'внж',
			'boravak',
			'боравак',
			'residence permit',
			'aufenthaltsgenehmigung',
			'oturum izni',
			'страховка',
			'осигурање',
			'osiguranje',
			'versicherung',
			'insurance',
			'sigorta',
			'полис',
			'sava',
			'lovćen',
			'uniqa',
			'generali',
			'grawe',
		],
	},
	{
		slug: 'child-healthcare-in-montenegro',
		titleKey: 'ChildHealthcareTitle',
		keywords: [
			'ребёнок',
			'ребенок',
			'дети',
			'djeca',
			'дјеца',
			'kind',
			'child',
			'çocuk',
			'педиатр',
			'pedijatar',
			'pädiatrie',
			'pediatrician',
			'прививки',
			'вакцинация',
			'vakcine',
			'impfung',
			'vaccination',
			'aşı',
			'справка в садик',
			'справка в школу',
			'vrtić',
			'kindergarten',
		],
	},
	{
		slug: 'mental-health-in-montenegro',
		titleKey: 'MentalHealthTitle',
		keywords: [
			'депрессия',
			'depresija',
			'депресија',
			'depression',
			'depresyon',
			'антидепрессанты',
			'antidepresivi',
			'antidepressiva',
			'тревога',
			'anksioznost',
			'психотерапия',
			'psihoterapija',
			'psychotherapie',
			'therapist',
			'выгорание',
			'паническая атака',
		],
	},
	{
		slug: 'dentistry-in-montenegro',
		titleKey: 'DentistryTitle',
		keywords: [
			'зубы',
			'зуб',
			'zub',
			'зуби',
			'zahn',
			'tooth',
			'teeth',
			'diş',
			'стоматолог',
			'stomatolog',
			'zahnarzt',
			'dentist',
			'имплант',
			'implant',
			'брекеты',
			'коронка',
			'пломба',
			'кариес',
		],
	},
	{
		slug: 'lab-tests-and-checkups',
		titleKey: 'LabTestsArticleTitle',
		keywords: [
			'чекап',
			'check-up',
			'checkup',
			'диспансеризация',
			'направление',
			'uput',
			'überweisung',
			'referral',
			'sevk',
			'лаборатория',
			'laboratorija',
			'labor',
			'laboratory',
			'laboratuvar',
		],
	},
	{
		slug: 'tourist-healthcare-in-montenegro',
		titleKey: 'TouristHealthcareTitle',
		keywords: [
			'турист',
			'turist',
			'tourist',
			'отпуск',
			'urlaub',
			'holiday',
			'tatil',
			'скорая',
			'hitna',
			'хитна',
			'notaufnahme',
			'emergency',
			'acil',
			'124',
			'ehic',
			'туристическая амбулатория',
			'turistička ambulanta',
		],
	},
	{
		slug: 'weekend-medical-help-in-montenegro',
		titleKey: 'WeekendMedicalHelpTitle',
		keywords: [
			'выходные',
			'vikend',
			'викенд',
			'wochenende',
			'weekend',
			'hafta sonu',
			'суббота',
			'воскресенье',
			'subota',
			'nedjelja',
			'праздники',
			'круглосуточно',
			'noćno dežurstvo',
			'ночью',
		],
	},
	{
		slug: 'healthcare-system-in-montenegro',
		titleKey: 'HealthcareSystemTitle',
		keywords: [
			'книжица',
			'knjižica',
			'књижица',
			'фзо',
			'fzo',
			'дом здравля',
			'dom zdravlja',
			'дом здравља',
			'izabrani doktor',
			'семейный врач',
			'обязательное страхование',
			'obavezno osiguranje',
		],
	},
	{
		slug: 'russian-speaking-doctors-in-montenegro',
		titleKey: 'RussianSpeakingDoctorsTitle',
		keywords: [
			'по-русски',
			'русский язык',
			'русскоговорящий',
			'ruski jezik',
			'руски језик',
			'russisch',
			'russian',
			'rusça',
		],
	},
	{
		slug: 'clinics-with-language-support',
		titleKey: 'ClinicsWithLanguageSupportTitle',
		keywords: [
			'английский',
			'engleski',
			'english',
			'englisch',
			'ingilizce',
			'немецкий',
			'njemački',
			'deutsch',
			'german',
			'турецкий',
			'turski',
			'türkçe',
			'итальянский',
			'французский',
			'переводчик',
			'jezik',
			'sprache',
			'language',
			'dil',
		],
	},
	{
		slug: 'healthcare-in-budva',
		titleKey: 'CityHcTitle_budva',
		keywords: ['budva', 'будва', 'будви', 'budvi', 'бечичи', 'bečići'],
	},
	{
		slug: 'healthcare-in-podgorica',
		titleKey: 'CityHcTitle_podgorica',
		keywords: [
			'podgorica',
			'подгорица',
			'подгорице',
			'podgorici',
			'клинический центр',
			'klinički centar',
		],
	},
	{
		slug: 'healthcare-in-kotor',
		titleKey: 'CityHcTitle_kotor',
		keywords: ['kotor', 'котор', 'которе', 'kotoru', 'доброта', 'dobrota'],
	},
	{
		slug: 'healthcare-in-bar',
		titleKey: 'CityHcTitle_bar',
		keywords: ['bar', 'бар', 'баре', 'baru', 'сутоморе', 'sutomore'],
	},
];
